# -*- coding: utf-8 -*-
"""Chatbot_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aNH5SHUTvi_kkOdT48p7sYBgc6sowJsl
"""

import logging
import os

import torch

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

from langchain.chains import RetrievalQA
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_ibm import WatsonxLLM

# Check for GPU availability and set the appropriate device for computation.
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

# Global variables
conversation_retrieval_chain = None
chat_history = []
llm_hub = None
embeddings = None


# Function to initialize the language model and its embeddings
def init_llm():
    global llm_hub, embeddings

    logger.info("Initializing WatsonxLLM and embeddings...")

    # Llama Model Configuration
    MODEL_ID = "meta-llama/llama-4-maverick-17b-128e-instruct-fp8"
    WATSONX_URL = "https://us-south.ml.cloud.ibm.com"
    PROJECT_ID = "skills-network"

    # Model parameters
    model_parameters = {
        "max_new_tokens": 256,
        "temperature": 0.1,
    }

    # Initialize Watsonx LLM
    llm_hub = WatsonxLLM(model_id=MODEL_ID, url=WATSONX_URL, project_id=PROJECT_ID, params=model_parameters)
    logger.debug("WatsonxLLM initialized: %s", llm_hub)

    # Initialize embeddings
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2", model_kwargs={"device": DEVICE}
    )
    logger.debug("Embeddings initialized with device: %s", DEVICE)


# Function to process a PDF document
def process_document(document_path):
    global conversation_retrieval_chain

    logger.info("Loading document from path: %s", document_path)

    loader = PyPDFLoader(document_path)
    documents = loader.load()
    logger.debug("Loaded %d document(s)", len(documents))

    # Split the document into chunks
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1024, chunk_overlap=64)
    texts = text_splitter.split_documents(documents)
    logger.debug("Document split into %d text chunks", len(texts))

    # Create Chroma vector store
    logger.info("Initializing Chroma vector store from documents...")
    db = Chroma.from_documents(texts, embedding=embeddings)
    logger.debug("Chroma vector store initialized.")

    # Optional: Log available collections
    try:
        collections = db._client.list_collections()  # _client is internal; adjust if needed
        logger.debug("Available collections in Chroma: %s", collections)
    except Exception as e:
        logger.warning("Could not retrieve collections from Chroma: %s", e)

    # Build the QA chain
    conversation_retrieval_chain = RetrievalQA.from_chain_type(
        llm=llm_hub,
        chain_type="stuff",
        retriever=db.as_retriever(search_type="mmr", search_kwargs={"k": 6, "lambda_mult": 0.25}),
        return_source_documents=False,
        input_key="question",
    )
    logger.info("RetrievalQA chain created successfully.")


# Function to process a user prompt
def process_prompt(prompt):
    global conversation_retrieval_chain
    global chat_history

    logger.info("Processing prompt: %s", prompt)

    output = conversation_retrieval_chain.invoke({"question": prompt, "chat_history": chat_history})
    answer = output["result"]
    logger.debug("Model response: %s", answer)

    # Update chat history
    chat_history.append((prompt, answer))
    logger.debug("Chat history updated. Total exchanges: %d", len(chat_history))

    return answer


# Initialize the language model
init_llm()
logger.info("LLM and embeddings initialization complete.")


def init_llm():
    global llm_hub, embeddings

    os.environ["HUGGINGFACEHUB_API_TOKEN"] = "YOUR API KEY"
    base_llm = HuggingfaceEndpoint(
        repo_id="",
        task="text_generation",
        huggingfacehub_api_token=os.environ["HUGGINGFACEHUB_API_TOKEN"],
        temperature=0.1,
        max_new_tokens=600,
    )

    llm_hub = ChatHuggingFace(llm=base_llm)
    embeddings = HuggingFaceEmbeddings(
        model_name="",
        model_kwargs={"device": DEVICE},
    )


# HuggingFace Version
import torch
from langchain_huggingface import (
    ChatHuggingFace,
    HuggingFaceEmbeddings,
    HuggingFaceEndpoint,
)

# Check for GPU availability
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

# Global variables
conversation_retrieval_chain = None
chat_history = []
llm_hub = None
embeddings = None


# Initialize the language model and embeddings
def init_llm():
    global llm_hub, embeddings

    os.environ["HUGGINGFACEHUB_API_TOKEN"] = "YOUR API KEY"

    base_llm = HuggingFaceEndpoint(
        repo_id="meta-llama/Llama-3.1-8B-Instruct",
        task="text-generation",
        huggingfacehub_api_token=os.environ["HUGGINGFACEHUB_API_TOKEN"],
        temperature=0.1,
        max_new_tokens=600,
    )

    # Wrap the base LLM with ChatHuggingFace
    llm_hub = ChatHuggingFace(llm=base_llm)

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2",
        model_kwargs={"device": DEVICE},
    )


# Process a PDF document
def process_document(document_path):
    global conversation_retrieval_chain

    loader = PyPDFLoader(document_path)
    documents = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1024, chunk_overlap=64)
    texts = text_splitter.split_documents(documents)

    db = Chroma.from_documents(texts, embedding=embeddings)

    conversation_retrieval_chain = RetrievalQA.from_chain_type(
        llm=llm_hub,
        chain_type="stuff",
        retriever=db.as_retriever(search_kwargs={"k": 3}),
        return_source_documents=False,
        input_key="question",
    )


# Process a user prompt
def process_prompt(prompt):
    global conversation_retrieval_chain, chat_history

    output = conversation_retrieval_chain.invoke({"question": prompt, "chat_history": chat_history})
    answer = output["result"]

    chat_history.append((prompt, answer))
    return answer.strip()


# Initialize LLM and embeddings
init_llm()

# server.py
import logging

import worker  # Import the worker module
from flask import Flask, jsonify, render_template, request
from flask_cors import CORS

# Initialize Flask app and CORS
app = Flask(__name__)
cors = CORS(app, resources={r"/*": {"origins": "*"}})
app.logger.setLevel(logging.ERROR)


# Define the route for the index page
@app.route("/", methods=["GET"])
def index():
    return render_template("index.html")  # Render the index.html template


# Define the route for processing messages
@app.route("/process-message", methods=["POST"])
def process_message_route():
    user_message = request.json["userMessage"]  # Extract the user's message from the request
    print("user_message", user_message)

    bot_response = worker.process_prompt(user_message)  # Process the user's message using the worker module

    # Return the bot's response as JSON
    return jsonify({"botResponse": bot_response}), 200


# Define the route for processing documents
@app.route("/process-document", methods=["POST"])
def process_document_route():
    # Check if a file was uploaded
    if "file" not in request.files:
        return jsonify(
            {
                "botResponse": "It seems like the file was not uploaded correctly, can you try "
                "again. If the problem persists, try using a different file"
            }
        ), 400

    file = request.files["file"]  # Extract the uploaded file from the request

    file_path = file.filename  # Define the path where the file will be saved
    file.save(file_path)  # Save the file

    worker.process_document(file_path)  # Process the document using the worker module

    # Return a success message as JSON
    return jsonify(
        {
            "botResponse": "Thank you for providing your PDF document. I have analyzed it, so now you can ask me any "
            "questions regarding it!"
        }
    ), 200


# Run the Flask app
if __name__ == "__main__":
    app.run(debug=True, port=8000, host="0.0.0.0")

"""
# Use Python 3.10 base image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy all project files
COPY . .

# Install dependencies from requirements.txt
# Then install specific versions of langchain, huggingface, transformers, etc.
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir \
       langchain==0.3.27 \
       langchain-core==0.3.80 \
       langchain-community==0.3.31 \
       langchain-huggingface==0.3.1 \
       langchain-text-splitters==0.3.11 \
       huggingface-hub==0.36.0 \
       tokenizers==0.19.1 \
       transformers==4.43.3 \
       sentence-transformers==2.7.0 \
       requests==2.32.5

# Expose port if needed (Flask default 8000)
EXPOSE 8000

# Run the server
CMD ["python", "-u", "server.py"]

docker build --no-cache -t build_chatbot_for_your_data .
docker run -p 8000:8000 build_chatbot_for_your_data
"""
