version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: documind-rag-chatbot:latest
    container_name: documind_rag_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
