from typing import List, Optional

from pydantic import BaseModel, Field


class QuestionRequest(BaseModel):
    userMessage: str = Field(..., description="The prompt or question submitted by the user.")


class QuestionResponse(BaseModel):
    botResponse: str = Field(..., description="The response generated by the RAG model.")


class HealthResponse(BaseModel):
    status: str = Field("healthy", description="Application health status.")
    llm_provider: str = Field(..., description="Currently active language model provider.")
    has_document_loaded: bool = Field(..., description="Indicates if a vector index is currently active.")
    loaded_document: Optional[str] = Field(None, description="Filename of the currently indexed PDF document.")
    use_parent_retriever: bool = Field(True, description="Indicates if Parent Document Retrieval is enabled.")


class ChatExchange(BaseModel):
    question: str = Field(..., description="The user's query.")
    answer: str = Field(..., description="The model's response.")


class HistoryResponse(BaseModel):
    history: List[ChatExchange] = Field(default=[], description="List of previous QA exchanges in this session.")
